# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20171118_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='post_number',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_number',
        ),
    ]
