# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 23:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20171118_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_id',
            field=models.CharField(help_text='Personal ID has to follow style yyyyMMdd-xxxx.', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Personal ID has to follow style yyyyMMdd-xxxx', regex='^\\d{8}-\\d{4}$')]),
        ),
    ]
