# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryproducts',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categoryproducts',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='grading',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='grading',
            old_name='user_id',
            new_name='user',
        ),
    ]
