# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productsnapshot',
            name='price_snapshot',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
