# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171110_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='shop.Category'),
        ),
        migrations.DeleteModel(
            name='CategoryProduct',
        ),
    ]
