# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171123_0107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set([('product', 'user_cart')]),
        ),
    ]
