# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 20:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_auto_20171201_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grading',
            new_name='Rating',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('user', 'product')]),
        ),
    ]
