# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20171201_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='grading',
            new_name='rating',
        ),
    ]
