# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducts',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderproducts',
            old_name='product_id',
            new_name='product',
        ),
    ]
