# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20171118_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('can_change_status', 'Can change status'),)},
        ),
    ]
