# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20171123_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('0', 'Verified'), ('1', 'Shipped'), ('2', 'Received'), ('3', 'Refunded')], default='0', max_length=1),
        ),
    ]
