# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[(0, 'Verified'), (1, 'Shipped'), (2, 'Received')], default='A', max_length=1),
        ),
    ]
